baseURL: 'https://cdutten.github.io/web/'
title: cdutten
enableRobotsTXT: true
languageCode: 'en-us'
theme: 'PaperMod'
params:
    defaultTheme: auto # to switch between dark or light according to browser theme
    ShowBreadCrumbs: true
    assets:
      favicon: "web/images/logo.png"
      favicon16x16: "web/images/logo.png"
      favicon32x32: "web/images/logo.png"
      apple_touch_icon: "web/images/logo.png"
      safari_pinned_tab: "web/images/logo.png"
    profileMode:
      enabled: true
      subtitle: "SysAdmin from Argentina living in the Česká republika. Trying to explain things that have been already explained"
      imageUrl: "images/logo.png" # optional
      imageTitle: "cdutten logo - anime style developer eating cheese while works"
      imageWidth: 320
      imageHeight: 320
      buttons:
        - name: Posts
          url: "/web/posts"
    socialIcons: # optional
    - name: "Twitch"
      url: "https://www.twitch.tv/cdutten"
    - name: Github
      url: "https://github.com/cdutten"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/cesar-dutten-543251120/"
    ShowReadingTime: true
