FROM python:3.10.5

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt &&\
    pip install -U Flask==2.1.2

COPY . .
ENV FLASK_APP=src/cduttenweb
ENV FLASK_ENV=development

EXPOSE 5000

RUN flask init-db &&\
    pip install -e .

CMD [ "flask", "run" ]

