apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cdutten-web
  name: cdutten-web
  namespace: cdutten-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdutten-web
  strategy: {}
  template:
    metadata:
      labels:
        app: cdutten-web
    spec:
      containers:
      - image: cdutten/web
        name: flask
        resources: {}
status: {}
